---
- name: Configure servers to send logs to central log management server
  hosts: log_clients
  become: yes
  vars:
    central_log_server_ip: "IP_DU_SERVEUR_CENTRAL"

  tasks:
    - name: Ensure Rsyslog is installed
      apt:
        name: rsyslog
        state: present
      notify:
        - Restart Rsyslog

    - name: Configure Rsyslog to send logs to central log management server
      lineinfile:
        path: /etc/rsyslog.conf
        state: present
        line: "*.* @@{{ central_log_server_ip }}:514"
      notify:
        - Restart Rsyslog

    - name: Ensure Logrotate is installed
      apt:
        name: logrotate
        state: present

  handlers:
    - name: Restart Rsyslog
      systemd:
        name: rsyslog
        state: restarted
